name: Deploy-To-Firebase

on: 
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.17.0
      uses: actions/setup-node@v1
      with:
        node-version: 18.17.0    
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: 1//0hGgSjG0W89GiCgYIARAAGBESNwF-L9IrIFjgdNgUtPLJTzc2XcPzB-2WYajL9XpAaX4tlx1u4ZGZ-InNO1kksMqi8gFqCJSKE6I
